# Generated by Django 4.1.2 on 2022-11-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='img',
            field=models.ImageField(default=None, upload_to='media'),
        ),
    ]
