# Generated by Django 4.1.2 on 2022-11-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_information_gender_alter_information_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='hobby',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
