# Generated by Django 4.1.2 on 2022-11-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_information_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='country',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
