# Generated by Django 4.1.2 on 2022-11-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PainPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_h', models.IntegerField()),
                ('seat_d', models.IntegerField()),
                ('seat_w', models.IntegerField()),
                ('backrest_h', models.IntegerField()),
                ('backrest_w', models.IntegerField()),
                ('backrest_l', models.IntegerField()),
                ('arm_h', models.IntegerField()),
                ('arm_l', models.IntegerField()),
                ('arm_distance', models.IntegerField()),
                ('age', models.IntegerField()),
                ('result', models.IntegerField()),
            ],
        ),
    ]
